spring.application.name=patient-service


spring.config.import=optional:configserver:http://localhost:8888

server.port=8081

management.endpoints.web.exposure.include=refresh

app.welcome=Chao mung toi BV RikkeiAcademy


# T?t tính n?ng b?t ??ng nh?p m?c ??nh c?a Spring Security
spring.security.user.name=admin
spring.security.user.password=admin

# Ho?c n?u phiên b?n Spring Boot c?a b?n cho phép b? qua hoàn toàn các endpoint:
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration